/*
 * efuse_priv.h - Internal eFuse register constants and controller commands
 *
 * Not part of the public API. Used only by efuse.c.
 */

#ifndef FESP_EFUSE_PRIV_H
#define FESP_EFUSE_PRIV_H

#include "chip_priv.h"
#include "efuse.h"

/* ============================================================================
 * eFuse controller command registers per chip type
 * ============================================================================
 */

#define FESP_EFUSE_CONF_REG_ESP32 (FESP_EFUSE_RD_REG_BASE_ESP32 + 0x0FC)
#define FESP_EFUSE_CMD_REG_ESP32 (FESP_EFUSE_RD_REG_BASE_ESP32 + 0x104)
#define FESP_EFUSE_CONF_WRITE_ESP32 0x5A5A
#define FESP_EFUSE_CONF_READ_ESP32 0x5AA5
#define FESP_EFUSE_CMD_WRITE_ESP32 0x2
#define FESP_EFUSE_CMD_READ_ESP32 0x1

#define FESP_EFUSE_CONF_REG_ESP32S2 (FESP_EFUSE_BASE_ESP32S2 + 0x1CC)
#define FESP_EFUSE_CMD_REG_ESP32S2 (FESP_EFUSE_BASE_ESP32S2 + 0x1D4)

#define FESP_EFUSE_CONF_REG_ESP32S3 (FESP_EFUSE_BASE_ESP32S3 + 0x1CC)
#define FESP_EFUSE_CMD_REG_ESP32S3 (FESP_EFUSE_BASE_ESP32S3 + 0x1D4)

#define FESP_EFUSE_CONF_REG_ESP32C2 (FESP_EFUSE_BASE_ESP32C2 + 0x08C)
#define FESP_EFUSE_CMD_REG_ESP32C2 (FESP_EFUSE_BASE_ESP32C2 + 0x094)

#define FESP_EFUSE_CONF_REG_ESP32C3 (FESP_EFUSE_BASE_ESP32C3 + 0x1CC)
#define FESP_EFUSE_CMD_REG_ESP32C3 (FESP_EFUSE_BASE_ESP32C3 + 0x1D4)

#define FESP_EFUSE_CONF_REG_ESP32C6 (FESP_EFUSE_BASE_ESP32C6 + 0x1CC)
#define FESP_EFUSE_CMD_REG_ESP32C6 (FESP_EFUSE_BASE_ESP32C6 + 0x1D4)

#define FESP_EFUSE_WRITE_OP_CODE 0x5A5A
#define FESP_EFUSE_READ_OP_CODE 0x5AA5
#define FESP_EFUSE_PGM_CMD 0x2
#define FESP_EFUSE_READ_CMD 0x1

/* ============================================================================
 * eFuse encryption field offsets and bit masks
 * ============================================================================
 */

/* ESP32 */
#define FESP_EFUSE_OFFS_FLASH_CRYPT_CNT_ESP32 0x00
#define FESP_EFUSE_MASK_FLASH_CRYPT_CNT_ESP32 (0x7FUL << 20)
#define FESP_EFUSE_OFFS_DISABLE_DL_ENCRYPT_ESP32 0x18
#define FESP_EFUSE_BIT_DISABLE_DL_ENCRYPT_ESP32 (1UL << 7)
#define FESP_EFUSE_OFFS_DISABLE_DL_DECRYPT_ESP32 0x18
#define FESP_EFUSE_BIT_DISABLE_DL_DECRYPT_ESP32 (1UL << 8)
#define FESP_EFUSE_OFFS_UART_DOWNLOAD_DIS_ESP32 0x00
#define FESP_EFUSE_BIT_UART_DOWNLOAD_DIS_ESP32 (1UL << 27)

/* ESP32-S2 */
#define FESP_EFUSE_OFFS_SPI_BOOT_CRYPT_CNT_ESP32S2 0x34
#define FESP_EFUSE_MASK_SPI_BOOT_CRYPT_CNT_ESP32S2 (7UL << 18)
#define FESP_EFUSE_OFFS_DIS_DL_MANUAL_ENCRYPT_ESP32S2 0x30
#define FESP_EFUSE_BIT_DIS_DL_MANUAL_ENCRYPT_ESP32S2 (1UL << 20)
#define FESP_EFUSE_OFFS_DIS_DOWNLOAD_MODE_ESP32S2 0x3C
#define FESP_EFUSE_BIT_DIS_DOWNLOAD_MODE_ESP32S2 (1UL << 4)
#define FESP_EFUSE_OFFS_ENABLE_SECURITY_DL_ESP32S2 0x3C
#define FESP_EFUSE_BIT_ENABLE_SECURITY_DL_ESP32S2 (1UL << 5)

/* ESP32-S3 */
#define FESP_EFUSE_OFFS_SPI_BOOT_CRYPT_CNT_ESP32S3 0x34
#define FESP_EFUSE_MASK_SPI_BOOT_CRYPT_CNT_ESP32S3 (7UL << 18)
#define FESP_EFUSE_OFFS_DIS_DL_MANUAL_ENCRYPT_ESP32S3 0x30
#define FESP_EFUSE_BIT_DIS_DL_MANUAL_ENCRYPT_ESP32S3 (1UL << 20)
#define FESP_EFUSE_OFFS_DIS_DOWNLOAD_MODE_ESP32S3 0x3C
#define FESP_EFUSE_BIT_DIS_DOWNLOAD_MODE_ESP32S3 (1UL << 4)
#define FESP_EFUSE_OFFS_ENABLE_SECURITY_DL_ESP32S3 0x3C
#define FESP_EFUSE_BIT_ENABLE_SECURITY_DL_ESP32S3 (1UL << 5)

/* ESP32-C2 */
#define FESP_EFUSE_OFFS_SPI_BOOT_CRYPT_CNT_ESP32C2 0x30
#define FESP_EFUSE_MASK_SPI_BOOT_CRYPT_CNT_ESP32C2 (7UL << 7)
#define FESP_EFUSE_OFFS_DIS_DL_MANUAL_ENCRYPT_ESP32C2 0x30
#define FESP_EFUSE_BIT_DIS_DL_MANUAL_ENCRYPT_ESP32C2 (1UL << 6)
#define FESP_EFUSE_OFFS_DIS_DOWNLOAD_MODE_ESP32C2 0x30
#define FESP_EFUSE_BIT_DIS_DOWNLOAD_MODE_ESP32C2 (1UL << 14)
#define FESP_EFUSE_OFFS_ENABLE_SECURITY_DL_ESP32C2 0x30
#define FESP_EFUSE_BIT_ENABLE_SECURITY_DL_ESP32C2 (1UL << 16)

/* ESP32-C3 */
#define FESP_EFUSE_OFFS_SPI_BOOT_CRYPT_CNT_ESP32C3 0x34
#define FESP_EFUSE_MASK_SPI_BOOT_CRYPT_CNT_ESP32C3 (7UL << 18)
#define FESP_EFUSE_OFFS_DIS_DL_MANUAL_ENCRYPT_ESP32C3 0x30
#define FESP_EFUSE_BIT_DIS_DL_MANUAL_ENCRYPT_ESP32C3 (1UL << 20)
#define FESP_EFUSE_OFFS_DIS_DOWNLOAD_MODE_ESP32C3 0x3C
#define FESP_EFUSE_BIT_DIS_DOWNLOAD_MODE_ESP32C3 (1UL << 0)
#define FESP_EFUSE_OFFS_ENABLE_SECURITY_DL_ESP32C3 0x3C
#define FESP_EFUSE_BIT_ENABLE_SECURITY_DL_ESP32C3 (1UL << 5)

/* ESP32-C6 */
#define FESP_EFUSE_OFFS_SPI_BOOT_CRYPT_CNT_ESP32C6 0x34
#define FESP_EFUSE_MASK_SPI_BOOT_CRYPT_CNT_ESP32C6 (7UL << 18)
#define FESP_EFUSE_OFFS_DIS_DL_MANUAL_ENCRYPT_ESP32C6 0x30
#define FESP_EFUSE_BIT_DIS_DL_MANUAL_ENCRYPT_ESP32C6 (1UL << 20)
#define FESP_EFUSE_OFFS_DIS_DOWNLOAD_MODE_ESP32C6 0x3C
#define FESP_EFUSE_BIT_DIS_DOWNLOAD_MODE_ESP32C6 (1UL << 0)
#define FESP_EFUSE_OFFS_ENABLE_SECURITY_DL_ESP32C6 0x3C
#define FESP_EFUSE_BIT_ENABLE_SECURITY_DL_ESP32C6 (1UL << 5)

/* ============================================================================
 * eFuse KEY_PURPOSE field offsets and masks
 * ============================================================================
 */

#define FESP_EFUSE_OFFS_FESP_KEY_PURPOSE_0 0x08
#define FESP_EFUSE_MASK_FESP_KEY_PURPOSE_0 (0x0FUL << 24)
#define FESP_EFUSE_OFFS_FESP_KEY_PURPOSE_1 0x08
#define FESP_EFUSE_MASK_FESP_KEY_PURPOSE_1 (0x0FUL << 28)
#define FESP_EFUSE_OFFS_FESP_KEY_PURPOSE_2 0x0C
#define FESP_EFUSE_MASK_FESP_KEY_PURPOSE_2 (0x0FUL << 0)
#define FESP_EFUSE_OFFS_FESP_KEY_PURPOSE_3 0x0C
#define FESP_EFUSE_MASK_FESP_KEY_PURPOSE_3 (0x0FUL << 4)
#define FESP_EFUSE_OFFS_FESP_KEY_PURPOSE_4 0x0C
#define FESP_EFUSE_MASK_FESP_KEY_PURPOSE_4 (0x0FUL << 8)
#define FESP_EFUSE_OFFS_FESP_KEY_PURPOSE_5 0x0C
#define FESP_EFUSE_MASK_FESP_KEY_PURPOSE_5 (0x0FUL << 12)

/* ============================================================================
 * eFuse JTAG and Secure Boot fields per chip type
 * ============================================================================
 */

/* ESP32 */
#define FESP_EFUSE_OFFS_JTAG_DISABLE_ESP32 0x18
#define FESP_EFUSE_BIT_JTAG_DISABLE_ESP32 (1UL << 6)
#define FESP_EFUSE_OFFS_ABS_DONE_0_ESP32 0x18
#define FESP_EFUSE_BIT_ABS_DONE_0_ESP32 (1UL << 4)
#define FESP_EFUSE_OFFS_ABS_DONE_1_ESP32 0x18
#define FESP_EFUSE_BIT_ABS_DONE_1_ESP32 (1UL << 5)

/* ESP32-S2 */
#define FESP_EFUSE_OFFS_DIS_PAD_JTAG_ESP32S2 0x30
#define FESP_EFUSE_BIT_DIS_PAD_JTAG_ESP32S2 (1UL << 19)
#define FESP_EFUSE_OFFS_SOFT_DIS_JTAG_ESP32S2 0x30
#define FESP_EFUSE_BIT_SOFT_DIS_JTAG_ESP32S2 (1UL << 17)
#define FESP_EFUSE_OFFS_DIS_FORCE_DOWNLOAD_ESP32S2 0x30
#define FESP_EFUSE_BIT_DIS_FORCE_DOWNLOAD_ESP32S2 (1UL << 12)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE0_ESP32S2 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE0_ESP32S2 (1UL << 21)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE1_ESP32S2 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE1_ESP32S2 (1UL << 22)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE2_ESP32S2 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE2_ESP32S2 (1UL << 23)
#define FESP_EFUSE_OFFS_SECURE_BOOT_EN_ESP32S2 0x38
#define FESP_EFUSE_BIT_SECURE_BOOT_EN_ESP32S2 (1UL << 20)
#define FESP_EFUSE_OFFS_SEC_BOOT_AGG_REVOKE_ESP32S2 0x38
#define FESP_EFUSE_BIT_SEC_BOOT_AGG_REVOKE_ESP32S2 (1UL << 21)

/* ESP32-S3 */
#define FESP_EFUSE_OFFS_DIS_PAD_JTAG_ESP32S3 0x30
#define FESP_EFUSE_BIT_DIS_PAD_JTAG_ESP32S3 (1UL << 19)
#define FESP_EFUSE_OFFS_SOFT_DIS_JTAG_ESP32S3 0x30
#define FESP_EFUSE_MASK_SOFT_DIS_JTAG_ESP32S3 (7UL << 16)
#define FESP_EFUSE_OFFS_DIS_FORCE_DOWNLOAD_ESP32S3 0x30
#define FESP_EFUSE_BIT_DIS_FORCE_DOWNLOAD_ESP32S3 (1UL << 12)
#define FESP_EFUSE_OFFS_DIS_USB_JTAG_ESP32S3 0x38
#define FESP_EFUSE_BIT_DIS_USB_JTAG_ESP32S3 (1UL << 22)
#define FESP_EFUSE_OFFS_DIS_USB_SER_JTAG_ROM_ESP32S3 0x3C
#define FESP_EFUSE_BIT_DIS_USB_SER_JTAG_ROM_ESP32S3 (1UL << 2)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE0_ESP32S3 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE0_ESP32S3 (1UL << 21)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE1_ESP32S3 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE1_ESP32S3 (1UL << 22)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE2_ESP32S3 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE2_ESP32S3 (1UL << 23)
#define FESP_EFUSE_OFFS_SECURE_BOOT_EN_ESP32S3 0x38
#define FESP_EFUSE_BIT_SECURE_BOOT_EN_ESP32S3 (1UL << 20)
#define FESP_EFUSE_OFFS_SEC_BOOT_AGG_REVOKE_ESP32S3 0x38
#define FESP_EFUSE_BIT_SEC_BOOT_AGG_REVOKE_ESP32S3 (1UL << 21)

/* ESP32-C2 */
#define FESP_EFUSE_OFFS_DIS_FORCE_DOWNLOAD_ESP32C2 0x30
#define FESP_EFUSE_BIT_DIS_FORCE_DOWNLOAD_ESP32C2 (1UL << 14)

/* ESP32-C3 */
#define FESP_EFUSE_OFFS_DIS_PAD_JTAG_ESP32C3 0x30
#define FESP_EFUSE_BIT_DIS_PAD_JTAG_ESP32C3 (1UL << 19)
#define FESP_EFUSE_OFFS_SOFT_DIS_JTAG_ESP32C3 0x30
#define FESP_EFUSE_MASK_SOFT_DIS_JTAG_ESP32C3 (7UL << 16)
#define FESP_EFUSE_OFFS_DIS_USB_JTAG_ESP32C3 0x30
#define FESP_EFUSE_BIT_DIS_USB_JTAG_ESP32C3 (1UL << 9)
#define FESP_EFUSE_OFFS_DIS_FORCE_DOWNLOAD_ESP32C3 0x30
#define FESP_EFUSE_BIT_DIS_FORCE_DOWNLOAD_ESP32C3 (1UL << 12)
#define FESP_EFUSE_OFFS_DIS_USB_SER_JTAG_ROM_ESP32C3 0x3C
#define FESP_EFUSE_BIT_DIS_USB_SER_JTAG_ROM_ESP32C3 (1UL << 2)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE0_ESP32C3 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE0_ESP32C3 (1UL << 21)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE1_ESP32C3 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE1_ESP32C3 (1UL << 22)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE2_ESP32C3 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE2_ESP32C3 (1UL << 23)
#define FESP_EFUSE_OFFS_SECURE_BOOT_EN_ESP32C3 0x38
#define FESP_EFUSE_BIT_SECURE_BOOT_EN_ESP32C3 (1UL << 20)
#define FESP_EFUSE_OFFS_SEC_BOOT_AGG_REVOKE_ESP32C3 0x38
#define FESP_EFUSE_BIT_SEC_BOOT_AGG_REVOKE_ESP32C3 (1UL << 21)

/* ESP32-C6 */
#define FESP_EFUSE_OFFS_DIS_PAD_JTAG_ESP32C6 0x30
#define FESP_EFUSE_BIT_DIS_PAD_JTAG_ESP32C6 (1UL << 19)
#define FESP_EFUSE_OFFS_SOFT_DIS_JTAG_ESP32C6 0x30
#define FESP_EFUSE_MASK_SOFT_DIS_JTAG_ESP32C6 (7UL << 16)
#define FESP_EFUSE_OFFS_DIS_USB_JTAG_ESP32C6 0x30
#define FESP_EFUSE_BIT_DIS_USB_JTAG_ESP32C6 (1UL << 9)
#define FESP_EFUSE_OFFS_DIS_FORCE_DOWNLOAD_ESP32C6 0x30
#define FESP_EFUSE_BIT_DIS_FORCE_DOWNLOAD_ESP32C6 (1UL << 12)
#define FESP_EFUSE_OFFS_DIS_USB_SER_JTAG_ROM_ESP32C6 0x3C
#define FESP_EFUSE_BIT_DIS_USB_SER_JTAG_ROM_ESP32C6 (1UL << 2)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE0_ESP32C6 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE0_ESP32C6 (1UL << 21)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE1_ESP32C6 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE1_ESP32C6 (1UL << 22)
#define FESP_EFUSE_OFFS_SEC_BOOT_KEY_REVOKE2_ESP32C6 0x34
#define FESP_EFUSE_BIT_SEC_BOOT_KEY_REVOKE2_ESP32C6 (1UL << 23)
#define FESP_EFUSE_OFFS_SECURE_BOOT_EN_ESP32C6 0x38
#define FESP_EFUSE_BIT_SECURE_BOOT_EN_ESP32C6 (1UL << 20)
#define FESP_EFUSE_OFFS_SEC_BOOT_AGG_REVOKE_ESP32C6 0x38
#define FESP_EFUSE_BIT_SEC_BOOT_AGG_REVOKE_ESP32C6 (1UL << 21)

#endif /* FESP_EFUSE_PRIV_H */
