"""
generate_test_data.py - Generate DEFLATE compressed test data

Generates various DEFLATE compressed data for testing the decompressor.
Output: C header file with test data arrays.
"""

import zlib
import struct

def compress_data(data, level=9):
    """Compress data using DEFLATE (raw deflate, no zlib header)"""
    # Use raw deflate (wbits=-15) to get pure DEFLATE stream
    compressor = zlib.compressobj(level, zlib.DEFLATED, -15)
    compressed = compressor.compress(data) + compressor.flush()
    return compressed

def to_c_array(name, data):
    """Convert bytes to C array definition"""
    lines = [f"static const BYTE {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + 16 < len(data):
            lines.append(f"    {hex_str},")
        else:
            lines.append(f"    {hex_str}")
    lines.append("};")
    return "\n".join(lines)

def main():
    tests = []

    # Test 1: Simple ASCII string
    data1 = b"Hello, World!"
    compressed1 = compress_data(data1)
    tests.append(("test_hello", data1, compressed1))

    # Test 2: Longer string with repetition
    data2 = b"The quick brown fox jumps over the lazy dog. " * 5
    compressed2 = compress_data(data2)
    tests.append(("test_repeat", data2, compressed2))

    # Test 3: Binary data
    data3 = bytes(range(256)) * 4
    compressed3 = compress_data(data3)
    tests.append(("test_binary", data3, compressed3))

    # Test 4: Single byte repeated
    data4 = b"\x00" * 1000
    compressed4 = compress_data(data4)
    tests.append(("test_zeros", data4, compressed4))

    # Test 5: Random-like data (using deterministic sequence)
    data5 = bytes([((i * 7 + 13) & 0xFF) for i in range(500)])
    compressed5 = compress_data(data5)
    tests.append(("test_pseudo_random", data5, compressed5))

    # Test 6: Small data (1 byte)
    data6 = b"X"
    compressed6 = compress_data(data6)
    tests.append(("test_single_byte", data6, compressed6))

    # Test 7: Data with all byte values
    data7 = bytes(range(256))
    compressed7 = compress_data(data7)
    tests.append(("test_all_bytes", data7, compressed7))

    # Generate C header
    output = []
    output.append("/*")
    output.append(" * test_data.h - Generated DEFLATE test data")
    output.append(" *")
    output.append(" * Auto-generated by generate_test_data.py")
    output.append(" * Do not edit manually.")
    output.append(" */")
    output.append("")
    output.append("#ifndef TEST_DATA_H")
    output.append("#define TEST_DATA_H")
    output.append("")
    output.append("#include <windows.h>")
    output.append("")
    output.append("/* Test data structure */")
    output.append("typedef struct {")
    output.append("    const char *name;")
    output.append("    const BYTE *original;")
    output.append("    size_t original_len;")
    output.append("    const BYTE *compressed;")
    output.append("    size_t compressed_len;")
    output.append("} TEST_DATA;")
    output.append("")

    # Generate compressed data arrays
    for name, original, compressed in tests:
        output.append(to_c_array(f"{name}_original", original))
        output.append("")
        output.append(to_c_array(f"{name}_compressed", compressed))
        output.append("")

    # Generate test data table
    output.append("/* Test data table */")
    output.append("static const TEST_DATA test_cases[] = {")
    for i, (name, original, compressed) in enumerate(tests):
        comma = "," if i < len(tests) - 1 else ""
        output.append(f'    {{ "{name}", {name}_original, sizeof({name}_original), {name}_compressed, sizeof({name}_compressed) }}{comma}')
    output.append("};")
    output.append("")
    output.append(f"#define TEST_CASE_COUNT {len(tests)}")
    output.append("")
    output.append("#endif /* TEST_DATA_H */")

    # Write to file
    with open("test_data.h", "w") as f:
        f.write("\n".join(output))

    # Print summary
    print("Generated test data:")
    for name, original, compressed in tests:
        ratio = len(compressed) / len(original) * 100 if len(original) > 0 else 0
        print(f"  {name}: {len(original)} -> {len(compressed)} bytes ({ratio:.1f}%)")

    print(f"\nTotal: {len(tests)} test cases")
    print("Output: test_data.h")

if __name__ == "__main__":
    main()
