/*
 * test_deflate.c - Unit tests for DEFLATE decompressor
 *
 * Tests the deflate decompressor with various block types and edge cases.
 * Uses real compressed data generated by Python zlib.
 */

#include <stdio.h>
#include <string.h>
#include <windows.h>
#include "../src/utils/deflate.h"
#include "test_data.h"

/* Test result tracking */
static int tests_passed = 0;
static int tests_failed = 0;

/* Test helper macro */
#define TEST_ASSERT(condition, message) \
    do { \
        if (condition) { \
            printf("  PASS: %s\n", message); \
            tests_passed++; \
        } else { \
            printf("  FAIL: %s\n", message); \
            tests_failed++; \
        } \
    } while (0)

/* Test 1: Uncompressed block (BTYPE=00) */
static void test_uncompressed_block(void)
{
    printf("\nTest 1: Uncompressed block\n");

    BYTE input[] = {
        0x01,       /* BFINAL=1, BTYPE=00 */
        0x05, 0x00, /* LEN = 5 */
        0xFA, 0xFF, /* NLEN = ~5 */
        'H', 'e', 'l', 'l', 'o'
    };

    BYTE output[32] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, input, sizeof(input), output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == 5, "Output length is 5");
    TEST_ASSERT(memcmp(output, "Hello", 5) == 0, "Output data matches 'Hello'");
}

/* Test 2: Real compressed data - Hello World */
static void test_real_hello(void)
{
    printf("\nTest 2: Real compressed data - Hello World\n");

    BYTE output[256] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, test_hello_compressed, sizeof(test_hello_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_hello_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_hello_original, sizeof(test_hello_original)) == 0,
                "Output data matches original");
}

/* Test 3: Real compressed data - Repeated string */
static void test_real_repeat(void)
{
    printf("\nTest 3: Real compressed data - Repeated string\n");

    BYTE output[1024] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, test_repeat_compressed, sizeof(test_repeat_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_repeat_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_repeat_original, sizeof(test_repeat_original)) == 0,
                "Output data matches original");
}

/* Test 4: Real compressed data - Binary data */
static void test_real_binary(void)
{
    printf("\nTest 4: Real compressed data - Binary data\n");

    BYTE output[2048] = {0};
    DEFLATE_CTX ctx;

    printf("  Original size: %zu\n", sizeof(test_binary_original));
    printf("  Compressed size: %zu\n", sizeof(test_binary_compressed));

    deflate_init(&ctx, test_binary_compressed, sizeof(test_binary_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    printf("  Output size: %zu\n", ctx.out_pos);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_binary_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_binary_original, sizeof(test_binary_original)) == 0,
                "Output data matches original");
}

/* Test 5: Real compressed data - Zeros (RLE) */
static void test_real_zeros(void)
{
    printf("\nTest 5: Real compressed data - Zeros (RLE)\n");

    BYTE output[2048] = {0};
    DEFLATE_CTX ctx;

    printf("  Original size: %zu\n", sizeof(test_zeros_original));
    printf("  Compressed size: %zu\n", sizeof(test_zeros_compressed));
    printf("  Compressed data: ");
    for (size_t i = 0; i < sizeof(test_zeros_compressed); i++) {
        printf("%02X ", test_zeros_compressed[i]);
    }
    printf("\n");

    deflate_init(&ctx, test_zeros_compressed, sizeof(test_zeros_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    printf("  Return code: %d\n", ret);
    printf("  Output size: %zu\n", ctx.out_pos);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_zeros_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_zeros_original, sizeof(test_zeros_original)) == 0,
                "Output data matches original");
}

/* Test 6: Real compressed data - Pseudo-random */
static void test_real_pseudo_random(void)
{
    printf("\nTest 6: Real compressed data - Pseudo-random\n");

    BYTE output[1024] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, test_pseudo_random_compressed, sizeof(test_pseudo_random_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_pseudo_random_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_pseudo_random_original, sizeof(test_pseudo_random_original)) == 0,
                "Output data matches original");
}

/* Test 7: Real compressed data - Single byte */
static void test_real_single_byte(void)
{
    printf("\nTest 7: Real compressed data - Single byte\n");

    BYTE output[256] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, test_single_byte_compressed, sizeof(test_single_byte_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_single_byte_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_single_byte_original, sizeof(test_single_byte_original)) == 0,
                "Output data matches original");
}

/* Test 8: Real compressed data - All byte values */
static void test_real_all_bytes(void)
{
    printf("\nTest 8: Real compressed data - All byte values\n");

    BYTE output[512] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, test_all_bytes_compressed, sizeof(test_all_bytes_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Decompression returns OK");
    TEST_ASSERT(ctx.out_pos == sizeof(test_all_bytes_original), "Output length matches original");
    TEST_ASSERT(memcmp(output, test_all_bytes_original, sizeof(test_all_bytes_original)) == 0,
                "Output data matches original");
}

/* Test 9: Empty input */
static void test_empty_input(void)
{
    printf("\nTest 9: Empty input\n");

    BYTE output[32] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, NULL, 0, output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_BAD_INPUT, "Empty input returns BAD_INPUT");
}

/* Test 10: Invalid block type (BTYPE=11) */
static void test_invalid_block_type(void)
{
    printf("\nTest 10: Invalid block type\n");

    BYTE input[] = { 0x07 };  /* BFINAL=1, BTYPE=11 */
    BYTE output[32] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, input, sizeof(input), output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_BAD_INPUT, "Invalid block type returns BAD_INPUT");
}

/* Test 11: Output buffer too small */
static void test_output_too_small(void)
{
    printf("\nTest 11: Output buffer too small\n");

    BYTE output[3] = {0};  /* Too small for 5 bytes */
    DEFLATE_CTX ctx;

    deflate_init(&ctx, test_hello_compressed, sizeof(test_hello_compressed),
                 output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_ERROR, "Small buffer returns ERROR");
}

/* Test 12: Multiple uncompressed blocks */
static void test_multiple_blocks(void)
{
    printf("\nTest 12: Multiple uncompressed blocks\n");

    BYTE input[] = {
        0x00,       /* BFINAL=0, BTYPE=00 */
        0x03, 0x00, /* LEN = 3 */
        0xFC, 0xFF, /* NLEN = ~3 */
        'H', 'e', 'l',
        0x01,       /* BFINAL=1, BTYPE=00 */
        0x02, 0x00, /* LEN = 2 */
        0xFD, 0xFF, /* NLEN = ~2 */
        'l', 'o'
    };

    BYTE output[32] = {0};
    DEFLATE_CTX ctx;

    deflate_init(&ctx, input, sizeof(input), output, sizeof(output));
    int ret = deflate_decompress(&ctx);

    TEST_ASSERT(ret == DEFLATE_OK, "Multiple blocks returns OK");
    TEST_ASSERT(ctx.out_pos == 5, "Output length is 5");
    TEST_ASSERT(memcmp(output, "Hello", 5) == 0, "Output data matches 'Hello'");
}

/* Main test runner */
int main(void)
{
    printf("=== DEFLATE Decompressor Unit Tests ===\n");
    printf("Using real compressed data from Python zlib\n");

    test_uncompressed_block();
    test_real_hello();
    test_real_repeat();
    test_real_binary();
    test_real_zeros();
    test_real_pseudo_random();
    test_real_single_byte();
    test_real_all_bytes();
    test_empty_input();
    test_invalid_block_type();
    test_output_too_small();
    test_multiple_blocks();

    printf("\n=== Test Results ===\n");
    printf("Passed: %d\n", tests_passed);
    printf("Failed: %d\n", tests_failed);
    printf("Total:  %d\n", tests_passed + tests_failed);

    return tests_failed > 0 ? 1 : 0;
}
